encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'ency'
urlpatterns = [
    # path("", views.index, name="index"),
    path("",views.IndexView.as_view(),name='index'),
    # path("wiki/<str:name>", views.wiki, name="wiki"),
    path("<int:pk>", views.WikiView.as_view(),name='wiki'),
    path('random_page',views.random_page, name='random_page'),
    path('new_page', views.new_page, name='new_page'),
    path('edit/<int:pk>',views.edit, name='edit'),
    path('delete/<int:pk>',views.ProcedimientoDeleteView.as_view(), name='delete'),
    path('logout',views.loggout, name = 'logout'),
    path('login',views.loggin, name = 'login'),
    path('buscar',views.buscar,name='buscar'),

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.contrib.auth.models import AbstractUser
import markdown2 as mk
# Create your models here.

class User(AbstractBaseUser):
    pass

class Procedimiento(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField(blank=False)

    def serialize(self):
        content = mk.markdown(self.content)
        # title = str(self.title).lower()
        title = str(self.title)
        return {
            'title':title,
            'content':content,
        }

    def __str__(self):
        return f'title: {self.title}'

encyclopedia/forms.py
from django import forms

class MyForm(forms.Form):
    Entry = forms.CharField()

class NewPageForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea)

encyclopedia/views.py
from http.client import REQUEST_ENTITY_TOO_LARGE
from django.shortcuts import render
from django.http import  HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
import markdown2 as mk
import random
from .models import Procedimiento
from .forms import MyForm, NewPageForm
from django.views.generic.edit import FormView
from django.contrib.auth import logout, authenticate, login

def buscar(request):
    name = request.POST['procedimiento']
    procedimientos = Procedimiento.objects.all()
    lista = []
    print(name)
    for n in procedimientos:

        if name == n.title:
            return HttpResponseRedirect(reverse('ency:wiki',args=(n.pk,)))
        else:
            if name in n.title:
                lista.append(n)
    if lista != []:
        return render(request,'encyclopedia/index.html',{"procedimiento_list":lista})
    else:
        return HttpResponseRedirect(reverse('ency:index'))
    pass

def loggout(request):
    logout(request)
    return HttpResponseRedirect(reverse('ency:index'))

def loggin(request):
    if request.method == 'POST':
        print('espost')
        previa = request.POST['fprevia']
        
        page = previa.split(request.headers['Origin'])[-1]
        username = request.POST['fusername']
        password = request.POST['fpassword']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            # return render(request, previa)
            print(page)
            if page != '/' and page != '/edit':
                return HttpResponseRedirect(reverse(f'ency:wiki',args=(int(page[1:]),)))
            else:
                return HttpResponseRedirect(reverse('ency:index'))
            
        else:
            
            print('distinto')
            context = {'username':username,
                        'error': 'Usuario o contraseña incorrecta!',
                        "previa":previa}
            return render(request,'encyclopedia/login.html',context)
            
    print(request.headers['Referer'])
    
    return render(request, 'encyclopedia/login.html',{'previa':request.headers['Referer']})

class IndexView(generic.ListView):
    template_name = 'encyclopedia/index.html'
    context_object_name = 'procedimiento_list'
    
    def get_queryset(self):
        return Procedimiento.objects.all()



class WikiView(generic.DetailView):
    model = Procedimiento
    template_name = 'encyclopedia/wiki.html'
   
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = context['object'].title
        content = context['object'].content
        pre_text = mk.markdown(f'# {title} \n{content}')
        context['pre_text'] = pre_text
        return context

def random_page(request):
    '''Esta funcion devuelve una wiki aleatoria de las existentes  '''
    l = [entry for entry in Procedimiento.objects.all()]
    num = random.randint(0,len(l)-1)
    entry = l[num]
    # print(l[num].pk)
    return HttpResponseRedirect(reverse('ency:wiki',args=(entry.pk,)))

def new_page(request):
    '''Esta funcion nos permite crear nuestra propia wiki, llenando un titulo
        para el titulo de la pagina y un contenido en formato Markdown para que
        el creador pueda desarrollar contenido mucho mas facil y rapido
        aqui pueden ir a una pagina acerca de este formato:
        https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax'''

    form  = MyForm()
    newPageForm = NewPageForm(request.POST)
    if request.method == 'POST':
        if newPageForm.is_valid():
            title = newPageForm.cleaned_data['title']
            content = newPageForm.cleaned_data['content']
            if Procedimiento.objects.filter(title=title).first() != None:
                # print()
                return render(request, 'encyclopedia/new_page.html', {
                    # 'form':form,  
                    'newPageForm':newPageForm,
                    'error':'Error the entry already exists!',
                })
            else:
                entry = Procedimiento.objects.create(title=title,content=content)
                entry.save()
                return HttpResponseRedirect(reverse('ency:wiki',args=(entry.pk,)))

    return render(request, 'encyclopedia/new_page.html', {
        # 'form':form,
        'newPageForm':NewPageForm()
    })

def edit(request,pk):
    '''Esta funcion nos permite editar una pagina visitada dandole al link
        "click hera for edit page" nos permite ir a una pagina para la ediccion
        de nuestra wiki'''
    print(pk)
    form = MyForm()
    newPageForm = NewPageForm(request.POST)
    if request.method == 'POST':
        if newPageForm.is_valid():
            title = newPageForm.cleaned_data['title']
            content = newPageForm.cleaned_data['content']
            entry = Procedimiento.objects.get(title=title)
            entry.content = content
            entry.save()
            return HttpResponseRedirect(reverse('ency:wiki',args=(pk,)))
    
    # title = request.headers['Referer'].split('/')[-1]
    entry = Procedimiento.objects.get(pk=pk)
    request.POST ={'title':entry.title,'content':entry.content, 'pk':entry.pk}
    return render(request, 'encyclopedia/edit.html', {
        'form': form,
        'newPageForm':NewPageForm(request.POST),
        'error':'',
        'pk':pk,
    })

class ProcedimientoDeleteView(generic.DeleteView):
    model = Procedimiento
    success_url = reverse_lazy('ency:index')

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}
  Editar procedimiento
{% endblock %}

{% block body %}
<form action="{% url 'ency:edit' pk %}" method="post">
  {% csrf_token %}
  {{ newPageForm.as_p }}
  <input type="submit" name="submit" value="submit">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
    
{% endblock %}

{% block body %}
    <h1>Procedimientos</h1>
    <ul>
        {% for entry in procedimiento_list %}
        <!-- <li><a href="wiki/{{entry.title}}">{{ entry.title }}</a></li> -->
        <li><a href="{% url 'ency:wiki'  entry.pk %}">{{ entry.title }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <style>
            #divlogin {
                height: 3em;
                background-color: black;
                text-align: right; 
                padding-right: 2em;
            }
            #spanlogin {
                color: aqua;

            }
        </style>
    </head>
    <body>
        <div id="divbanner">
            <img src="{% static 'encyclopedia/images/banner_sismologico.jpg' %}" alt="Escudos de la UASD y el CNS" width="100%">
        </div>
        {% if user.is_authenticated %}
            <div id="divlogin" >
                <span id="spanlogin">Logged: {{ user }}</span><br>
                <span><a href="{% url 'ency:logout' %}">Logout</a><span>
            </div>
        {% else %}
            <div id="divlogin" >
                <span id="spanlogin"> Not Logged </span>  <br>
                <a href="{% url 'ency:login' %}">Loguearse aqui</a>
            </div>
        {% endif %}

        <div class="row">
            
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki-CNS</h2>
                 <form action="{% url 'ency:buscar' %}" method="post">
                    {% csrf_token %}
                    <!-- {{ form.as_p }} -->
                    <label for="procedimiento">Procedimiento</label>
                    <input type="text" id="procedimiento" name="procedimiento">
                    <input type="submit" value="aceptar">
                </form>
                <hr>
                <div>
                    <a href="{% url 'ency:index' %}">Home</a>
                </div>
                {% if user.is_authenticated %}
                <div>
                    <a href="{% url 'ency:new_page' %}">Nuevo Procedimiento</a>
                </div>
                {% endif %}
                <div>
                    <a href="{% url 'ency:random_page' %}">Procedimiento Random</a>
                </div>
                {% block nav %}
                {% endblock %}
                
            </div>
            
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #form_login {
            font-size: 2em;
            /* max-width: 15em; */

            width: 15em;
            height: 60em;
        }
        div {
            margin-left: auto;
            margin-right: auto;
        }
    </style>
</head>
<body>
    <div>
        {% if error %}
            <form id = 'form_login' action="{% url 'ency:login' %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend>Ingrese sus datos:</legend>
                    <label for="fusername">Username:</label>
                    <input type="text" id="fusername" name="fusername" value = '{{ username }}'><br><br>
                    <label for="fpassword">Password:</label>
                    <input type="text" id="fpassword" name="fpassword" ><br><br>
                    <input type="hidden" name="fprevia" value="{{ previa }}" >
                    <input type="submit" value="Submit">
                
                </fieldset>
                <span><strong>{{ error }}</strong></span>
            </form>
            
        {% else %}
            <form id = 'form_login' action="{% url 'ency:login' %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend>Ingrese sus datos:</legend>
                    <label for="fusername">Username:</label>
                    <input type="text" id="fusername" name="fusername" ><br><br>
                    <label for="fpassword">Password:</label>
                    <input type="password" id="fpassword" name="fpassword"><br><br>
                    <input type="hidden" name="fprevia" value="{{ previa }}" >
                    <input type="submit" value="Submit">

                </fieldset>
            </form>
        {% endif %}
        
            
    </div>
</body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}
Crear Procedimiento
{% endblock %}

{% block body %}
{% if  error  %}
  <div class="alert alert-danger" role="alert">
    {{error}}
  </div>
{% endif %}
<form action="{% url 'ency:new_page' %}" method="post">
  {% csrf_token %}
  {{ newPageForm.as_p }}
  <br>
  <input type="submit" name="submit" value="submit">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/procedimiento_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

encyclopedia/templates/encyclopedia/random_page.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}<h1>Procedimiento</h1>{% endblock %}
{% block body %}
{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ procedimiento.title }}
{% endblock %}

{% block body %}
   <div><pre>{{ pre_text|safe }}</pre></div> 
    
        <div class="edit_entry">
            <br><br><br><hr>
    {% if user.is_authenticated %}
            <a style="margin-right: 4em;" href="{% url 'ency:edit' procedimiento.pk %}">Editar</a>
            <a href="{% url 'ency:delete' procedimiento.pk %}">Eliminar</a>

        </div>
    {% endif %}
{% endblock %}